package com.ipanda.desktop

import androidx.compose.animation.*
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import java.util.prefs.Preferences
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.WindowPlacement
import androidx.compose.ui.window.application
import androidx.compose.ui.window.rememberWindowState
import com.ipanda.crawler.MovieCrawler
import com.ipanda.crawler.StreamSniffer
import com.ipanda.data.repository.MovieRepositoryImpl
import com.ipanda.data.repository.StreamRepositoryImpl
import com.ipanda.desktop.screen.MovieDetailScreen
import com.ipanda.desktop.screen.MovieListScreen
import com.ipanda.desktop.screen.PlayerScreen
import com.ipanda.desktop.theme.AppTheme
import com.ipanda.domain.StreamSource
import kotlinx.coroutines.launch
import com.ipanda.data.local.getDatabaseBuilder
import com.ipanda.data.local.getRoomDatabase
import com.ipanda.data.repository.FavoriteRepositoryImpl
import com.ipanda.domain.repository.FavoriteRepository

// ── Navigation ──────────────────────────────────────────────────────

sealed class Screen {
    data object MovieList : Screen()
    data class MovieDetail(val movieUrl: String) : Screen()
    data class Player(val streamSources: List<StreamSource>, val episodeTitle: String) : Screen()
}

// ── Entry Point ─────────────────────────────────────────────────────

fun main() {
    // Read Browserless config from BuildConfig (generated by Gradle)
    val defaultKey = BuildConfig.BROWSERLESS_API_KEY
    val defaultEndpoint = BuildConfig.BROWSERLESS_ENDPOINT

    val prefs = Preferences.userRoot().node("com.ipanda.desktop.settings")

    val streamSniffer = StreamSniffer(
        browserlessApiKey = prefs.get("BROWSERLESS_KEY", "").takeIf { it.isNotBlank() } ?: defaultKey,
        browserlessEndpoint = prefs.get("BROWSERLESS_ENDPOINT", "").takeIf { it.isNotBlank() } ?: defaultEndpoint
    )

    // Create dependencies
    val movieRepository = MovieRepositoryImpl(MovieCrawler())
    val streamRepository = StreamRepositoryImpl(streamSniffer)
    
    val database = com.ipanda.data.local.getRoomDatabase(com.ipanda.data.local.getDatabaseBuilder())
    val favoriteRepository = com.ipanda.data.repository.FavoriteRepositoryImpl(database)

    application {
        val windowState = rememberWindowState(width = 1200.dp, height = 800.dp)
        var isFullScreen by remember { mutableStateOf(false) }

        LaunchedEffect(isFullScreen) {
            windowState.placement = if (isFullScreen) {
                WindowPlacement.Fullscreen
            } else {
                WindowPlacement.Floating
            }
        }

        Window(
            onCloseRequest = ::exitApplication,
            title = "iPanda - Movie Player",
            state = windowState
        ) {
            AppTheme {
                var currentScreen by remember { mutableStateOf<Screen>(Screen.MovieList) }
                var showSettingsDialog by remember { mutableStateOf(false) }

                if (showSettingsDialog) {
                    var apiKeyInput by remember { mutableStateOf(prefs.get("BROWSERLESS_KEY", "")) }
                    var endpointInput by remember { mutableStateOf(prefs.get("BROWSERLESS_ENDPOINT", "")) }

                    AlertDialog(
                        onDismissRequest = { showSettingsDialog = false },
                        title = { Text("Cài đặt") },
                        text = {
                            Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                                OutlinedTextField(
                                    value = apiKeyInput,
                                    onValueChange = { apiKeyInput = it },
                                    label = { Text("Browserless API Key") },
                                    singleLine = true
                                )
                                OutlinedTextField(
                                    value = endpointInput,
                                    onValueChange = { endpointInput = it },
                                    label = { Text("Browserless Endpoint") },
                                    singleLine = true
                                )
                                val coroutineScope = rememberCoroutineScope()
                                Button(
                                    onClick = {
                                        coroutineScope.launch {
                                            streamRepository.clearCache()
                                        }
                                    },
                                    modifier = Modifier.padding(top = 8.dp)
                                ) {
                                    Text("Xóa Cache Stream")
                                }
                            }
                        },
                        confirmButton = {
                            Button(onClick = {
                                val finalKey = apiKeyInput.takeIf { it.isNotBlank() } ?: defaultKey
                                val finalEndpoint = endpointInput.takeIf { it.isNotBlank() } ?: defaultEndpoint
                                
                                prefs.put("BROWSERLESS_KEY", apiKeyInput)
                                prefs.put("BROWSERLESS_ENDPOINT", endpointInput)
                                
                                streamSniffer.browserlessApiKey = finalKey
                                streamSniffer.browserlessEndpoint = finalEndpoint
                                
                                showSettingsDialog = false
                            }) {
                                Text("Lưu")
                            }
                        },
                        dismissButton = {
                            TextButton(onClick = { showSettingsDialog = false }) {
                                Text("Hủy")
                            }
                        }
                    )
                }

                AnimatedContent(
                    targetState = currentScreen,
                    modifier = Modifier.fillMaxSize(),
                    transitionSpec = {
                        fadeIn(animationSpec = tween(200)) togetherWith
                            fadeOut(animationSpec = tween(200))
                    }
                ) { screen ->
                    when (screen) {
                        is Screen.MovieList -> {
                            isFullScreen = false
                            MovieListScreen(
                                movieRepository = movieRepository,
                                favoriteRepository = favoriteRepository,
                                onMovieClick = { movie ->
                                    currentScreen = Screen.MovieDetail(movie.url)
                                },
                                onOpenSettings = { showSettingsDialog = true }
                            )
                        }
                        is Screen.MovieDetail -> {
                            isFullScreen = false
                            MovieDetailScreen(
                                movieUrl = screen.movieUrl,
                                movieRepository = movieRepository,
                                streamRepository = streamRepository,
                                favoriteRepository = favoriteRepository,
                                onBack = { currentScreen = Screen.MovieList },
                                onPlayStream = { streams, title ->
                                    currentScreen = Screen.Player(streams, title)
                                }
                            )
                        }
                        is Screen.Player -> {
                            PlayerScreen(
                                streamSources = screen.streamSources,
                                episodeTitle = screen.episodeTitle,
                                isFullScreen = isFullScreen,
                                onToggleFullScreen = { isFullScreen = !isFullScreen },
                                onBack = { 
                                    isFullScreen = false
                                    currentScreen = Screen.MovieList 
                                }
                            )
                        }
                    }
                }
            }
        }
    }
}

// Helper for animation spec
private fun <T> tween(durationMillis: Int) = androidx.compose.animation.core.tween<T>(durationMillis)
