package com.ipanda.desktop

import androidx.compose.animation.*
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.key
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import java.util.prefs.Preferences
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.WindowPlacement
import androidx.compose.ui.window.application
import androidx.compose.ui.window.rememberWindowState
import com.ipanda.crawler.MovieCrawler
import com.ipanda.crawler.StreamSniffer
import com.ipanda.data.repository.MovieRepositoryImpl
import com.ipanda.data.repository.StreamRepositoryImpl
import com.ipanda.desktop.screen.MovieDetailScreen
import com.ipanda.desktop.screen.MovieListScreen
import com.ipanda.desktop.screen.PlayerScreen
import com.ipanda.desktop.theme.AppTheme
import com.ipanda.domain.StreamSource
import kotlinx.coroutines.launch
import com.ipanda.data.local.getDatabaseBuilder
import com.ipanda.data.local.getRoomDatabase
import com.ipanda.data.repository.FavoriteRepositoryImpl
import com.ipanda.domain.repository.FavoriteRepository

// ── Navigation ──────────────────────────────────────────────────────

sealed class Screen {
    data object MovieList : Screen()
    data class MovieDetail(val movieUrl: String) : Screen()
}

data class PlayerWindowData(
    val id: String = java.util.UUID.randomUUID().toString(),
    val streamSources: List<StreamSource>,
    val episodeTitle: String
)

data class WebViewWindowData(
    val id: String = java.util.UUID.randomUUID().toString(),
    val url: String,
    val title: String
)

// ── Entry Point ─────────────────────────────────────────────────────

fun main() {
    // Read Browserless config from BuildConfig (generated by Gradle)
    val defaultKey = BuildConfig.BROWSERLESS_API_KEY
    val defaultEndpoint = BuildConfig.BROWSERLESS_ENDPOINT

    val prefs = Preferences.userRoot().node("com.ipanda.desktop.settings")

    val streamSniffer = StreamSniffer(
        browserlessApiKey = prefs.get("BROWSERLESS_KEY", "").takeIf { it.isNotBlank() } ?: defaultKey,
        browserlessEndpoint = prefs.get("BROWSERLESS_ENDPOINT", "").takeIf { it.isNotBlank() } ?: defaultEndpoint
    )

    // Create dependencies
    val movieRepository = MovieRepositoryImpl(MovieCrawler())
    val streamRepository = StreamRepositoryImpl(streamSniffer)
    
    val database = com.ipanda.data.local.getRoomDatabase(com.ipanda.data.local.getDatabaseBuilder())
    val favoriteRepository = com.ipanda.data.repository.FavoriteRepositoryImpl(database)

    application {
        val openPlayers = remember { mutableStateListOf<PlayerWindowData>() }
        val openWebViews = remember { mutableStateListOf<WebViewWindowData>() }

        // Main App Window
        val windowState = rememberWindowState(width = 1200.dp, height = 800.dp)
        Window(
            onCloseRequest = ::exitApplication,
            title = "iPanda - Movie Player",
            state = windowState
        ) {
            AppTheme {
                var currentScreen by remember { mutableStateOf<Screen>(Screen.MovieList) }
                var showSettingsDialog by remember { mutableStateOf(false) }

                if (showSettingsDialog) {
                    var apiKeyInput by remember { mutableStateOf(prefs.get("BROWSERLESS_KEY", "")) }
                    var endpointInput by remember { mutableStateOf(prefs.get("BROWSERLESS_ENDPOINT", "")) }

                    AlertDialog(
                        onDismissRequest = { showSettingsDialog = false },
                        title = { Text("Cài đặt") },
                        text = {
                            Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                                OutlinedTextField(
                                    value = apiKeyInput,
                                    onValueChange = { apiKeyInput = it },
                                    label = { Text("Browserless API Key") },
                                    singleLine = true
                                )
                                OutlinedTextField(
                                    value = endpointInput,
                                    onValueChange = { endpointInput = it },
                                    label = { Text("Browserless Endpoint") },
                                    singleLine = true
                                )
                                val coroutineScope = rememberCoroutineScope()
                                Button(
                                    onClick = {
                                        coroutineScope.launch {
                                            streamRepository.clearCache()
                                        }
                                    },
                                    modifier = Modifier.padding(top = 8.dp)
                                ) {
                                    Text("Xóa Cache Stream")
                                }
                            }
                        },
                        confirmButton = {
                            Button(onClick = {
                                val finalKey = apiKeyInput.takeIf { it.isNotBlank() } ?: defaultKey
                                val finalEndpoint = endpointInput.takeIf { it.isNotBlank() } ?: defaultEndpoint
                                
                                prefs.put("BROWSERLESS_KEY", apiKeyInput)
                                prefs.put("BROWSERLESS_ENDPOINT", endpointInput)
                                
                                streamSniffer.browserlessApiKey = finalKey
                                streamSniffer.browserlessEndpoint = finalEndpoint
                                
                                showSettingsDialog = false
                            }) {
                                Text("Lưu")
                            }
                        },
                        dismissButton = {
                            TextButton(onClick = { showSettingsDialog = false }) {
                                Text("Hủy")
                            }
                        }
                    )
                }

                AnimatedContent(
                    targetState = currentScreen,
                    modifier = Modifier.fillMaxSize(),
                    transitionSpec = {
                        fadeIn(animationSpec = tween(200)) togetherWith
                            fadeOut(animationSpec = tween(200))
                    }
                ) { screen ->
                    when (screen) {
                        is Screen.MovieList -> {
                            MovieListScreen(
                                movieRepository = movieRepository,
                                favoriteRepository = favoriteRepository,
                                onMovieClick = { movie ->
                                    currentScreen = Screen.MovieDetail(movie.url)
                                },
                                onOpenSettings = { showSettingsDialog = true }
                            )
                        }
                        is Screen.MovieDetail -> {
                            MovieDetailScreen(
                                movieUrl = screen.movieUrl,
                                movieRepository = movieRepository,
                                streamRepository = streamRepository,
                                favoriteRepository = favoriteRepository,
                                onBack = { currentScreen = Screen.MovieList },
                                onPlayStream = { streams, title ->
                                    openPlayers.add(PlayerWindowData(streamSources = streams, episodeTitle = title))
                                }
                            )
                        }
                    }
                }
            }
        }

        // Dedicated Player Windows
        openPlayers.forEach { player ->
            key(player.id) {
                val playerState = rememberWindowState(width = 1280.dp, height = 720.dp)
                var isPlayerFullScreen by remember { mutableStateOf(true) } // Auto-fullscreen for player

                LaunchedEffect(isPlayerFullScreen) {
                    playerState.placement = if (isPlayerFullScreen) {
                        WindowPlacement.Fullscreen
                    } else {
                        WindowPlacement.Floating
                    }
                }

                Window(
                    onCloseRequest = { openPlayers.remove(player) },
                    title = "Playing: ${player.episodeTitle}",
                    state = playerState
                ) {
                    AppTheme {
                        PlayerScreen(
                            streamSources = player.streamSources,
                            episodeTitle = player.episodeTitle,
                            isFullScreen = isPlayerFullScreen,
                            onToggleFullScreen = { isPlayerFullScreen = !isPlayerFullScreen },
                            onOpenWebView = { url ->
                                openWebViews.add(WebViewWindowData(url = url, title = player.episodeTitle))
                                openPlayers.remove(player)
                            },
                            onBack = { openPlayers.remove(player) }
                        )
                    }
                }
            }
        }

        // Dedicated WebView Windows
        openWebViews.forEach { webView ->
            key(webView.id) {
                val webState = rememberWindowState(width = 1280.dp, height = 720.dp)
                Window(
                    onCloseRequest = { openWebViews.remove(webView) },
                    title = "Browser: ${webView.title}",
                    state = webState
                ) {
                    AppTheme {
                        // Reusing the WebView part from PlayerScreen logic
                        com.ipanda.desktop.screen.WebViewScreen(
                            url = webView.url,
                            title = webView.title,
                            onBack = { openWebViews.remove(webView) }
                        )
                    }
                }
            }
        }
    }
}

// Helper for animation spec
private fun <T> tween(durationMillis: Int) = androidx.compose.animation.core.tween<T>(durationMillis)
